{
	"version": 1739967445,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/play-sheet0.png",
		"images/bg-sheet0.png",
		"images/wtfcoin-sheet0.png",
		"images/wtfcoin-sheet1.png",
		"images/web.png",
		"images/wtfcoin2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/spiderman-sheet0.png",
		"images/hand-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/game over (1).m4a",
		"media/game over (1).ogg",
		"media/web shoot (1).m4a",
		"media/web shoot (1).ogg",
		"media/thank you 1.m4a",
		"media/thank you 1.ogg",
		"media/thank you 2.m4a",
		"media/thank you 2.ogg",
		"media/thank you 3.m4a",
		"media/thank you 3.ogg",
		"media/gwen scream.m4a",
		"media/gwen scream.ogg",
		"media/bg.m4a",
		"media/bg.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}